<?php defined('SYSPATH') or die('No direct script access.');

/**
 * Class Controller_Forms_Ajax
 *
 * @copyright raisoft
 * @author Nikolai Turov
 * @version 0.0.0
 */

class Controller_Forms_Ajax extends Ajax
{
    CONST CAN_CONDUCT_A_SURVEY = 36;
    public $pension  = null;
    public $usersIDs = null;

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub

        self::hasAccess(self::CAN_CONDUCT_A_SURVEY);

        $pension = Arr::get($_POST,'pension');
        $this->pension = new Model_Pension($pension);

        if (!$this->pension->id) {
            $response = new Model_Response_Pensions('PENSION_DOES_NOT_EXISTED_ERROR', 'error');
            $this->response->body(@json_encode($response->get_response()));
            return;
        }

        $this->usersIDs = Model_UserPension::getUsers($this->pension->id);

        if (!(in_array($this->user->id, $this->usersIDs))) {
            throw new HTTP_Exception_403();
        }
    }

    /**
     * Creating new Long-Term-Form
     */
    public function action_longterm_create()
    {
        $type    = Arr::get($_POST,'type');
        $patient = Arr::get($_POST,'patient');

        if (empty($type)) {
            $response = new Model_Response_Longtermform('FORM_TYPE_EMPTY_ERROR', 'error');
            $this->response->body(@json_encode($response->get_response()));
            return;
        }

        $patient = new Model_Patient($patient);

        if (!$patient->id) {
            $response = new Model_Response_Patients('PATIENTS_DOES_NOT_EXISTED_ERROR', 'error');
            $this->response->body(@json_encode($response->get_response()));
            return;
        }

        $count_forms = $this->redis->get(self::REDIS_PACKAGE . ':pensions:' . $this->pension->id . ':longtermforms');
        $count_forms = $count_forms == false ? 1 : $count_forms + 1;
        $this->redis->set(self::REDIS_PACKAGE . ':pensions:' . $this->pension->id . ':longtermforms', $count_forms);

        $form = new Model_LongTermForm();
        $form->id      = $count_forms;
        $form->patient = $patient->id;
        $form->pension = $this->pension->id;
        $form->type    = $type;
        $form->creator = $this->user->id;
        $form->save();

        $response = new Model_Response_Longtermform('FORM_CREATED_SUCCESS', 'success', array('id' => $count_forms));
        $this->response->body(@json_encode($response->get_response()));
    }

    public function action_update()
    {

    }

    public function action_get()
    {

    }

}